import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/navbar_layout";
import { Jost } from 'next/font/google';

const jost = Jost({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "DevLink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
